general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 11
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]
padding.x = 2
padding.y = 2
decorations = "None"
opacity = 0.95
blur = true

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
