set -g history-limit 1000
set -g default-terminal "xterm-256color"
set -g base-index 1
set -g pane-base-index 1
set -g xterm-keys on
set -g mouse on
bind-key C-d detach-client
bind-key C-p paste-buffer
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'
set -g pane-border-style 'fg=colour238,bg=colour235'
set -g pane-active-border-style 'fg=colour51,bg=colour236'
set -g status-right ''
