theme = "rose_pine"

[keys.normal]
"S-v" = ["extend_to_line_bounds", "select_mode"]
"r" = "rename_symbol"

[keys.insert]
"esc" = ["normal_mode"]

#[keys.normal.space]
[keys.normal.space]
p = ["changed_file_picker"]

#layer2
space.h = ":set-language helm"
space.y = ":set-language yaml"

#layer3
space.space.r = [":config-reload"]


[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
gutters = ["line-numbers", "spacer"]
idle-timeout = 1
#bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"
max-wrap = 10
prefix-len = 1

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
snippets = true

[editor.soft-wrap]
enable = true
max-wrap = 120 # increase value to reduce forced mid-word wrapping
max-indent-retain = 120
wrap-indicator = ">> "  # set wrap-indicator to "" to hide it

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.file-picker]
hidden = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "bar"

[editor.search]
smart-case = true

[editor.statusline]
left = ["spinner","file-modification-indicator", "file-name", "version-control"]
center = []
right = [ "selections",  "file-encoding", "file-line-ending","spacer" ]
separator = "││"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
