#remap prefix
unbind C-b
unbind '"'
unbind %

#Binds
set -g prefix M-Space
bind | split-window -h
bind - split-window -v
bind r source-file ~/.tmux.conf
bind / command-prompt "split-window 'exec man %%'"
bind-key k confirm kill-window
bind-key S confirm kill-server
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

#Options
set -s escape-time 0
set -g default-terminal "xterm-256color"
set -g set-titles off
set -g history-limit 5000
set -g bell-action any
set -g display-panes-time 2000
set -g visual-activity on
set -g visual-bell on
setw -g monitor-activity on
setw -g mode-keys vi
setw -g aggressive-resize on
setw -g clock-mode-colour green
setw -g clock-mode-style 24

#Status bar
set -g status-interval 5
set -g status-justify centre
set -g status-left-length 90
set -g status-right-length 100
set -g status-right ""
set -g status-left ""
set -g status-left '#[fg=grey]#[bg=default][#H]#[default]'
set -g status-right '#[fg=default]#[bg=default][VPN #[default]#[fg=default]#[bg=default]#(ip -4 -o addr show tun0 2>/dev/null | cut -d " " -f 7)]#[default]#[fg=default]#[bg=red][#(acpi -b | cut -d " " -f 4 | tr -d ",")]#[default] #[fg-white]#[bg=magenta] %H:%M #[default]'
set -g window-status-format "[#I #W #F]"
set -g window-status-current-format "[#I #W #F]#[default]"
