"Basic settings
set nocompatible
filetype indent on
syntax enable
set noerrorbells
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set t_Co=256
set noshowmode
set nu
set colorcolumn=120
highlight CursorColumn ctermbg=0 guibg=lightgrey
set cursorline
hi cursorline cterm=none term=none
highlight CursorLine ctermbg=234 guibg=#303000
set backspace=2
set hidden
set lazyredraw
set wildmenu
set showtabline=1

"indenting
set tabstop=4
set softtabstop=4
set expandtab
set smartindent

"encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set fileformats=unix,dos,mac

"searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Key maps
let mapleader=" "
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>u :UndotreeShow<CR>
nnoremap <leader>pv :NERDTreeMirror<CR>:NERDTreeFocus<CR>
nnoremap <silent> <Leader>+ :vertical resize +5<CR>
nnoremap <silent> <Leader>- :vertical resize -5<CR>

" VimPLug
let vimplug_exists=expand('~/.vim/autoload/plug.vim')

if !filereadable(vimplug_exists)
    if !executable("curl")
        echoerr "You have to install curl or install vim-plug by yourself!"
        execute "q!"
    endif
    echo "Installing vim-plug..."
    echo ""
    silent exec "!\curl -fLo " . vimplug_exists . " --create-dirs https://raw.github.com/junegunn/vim-plug/master/plug.vim"
    let g:not_finish_vimplug = "yes"
    autocmd VimEnter * PlugInstall
endif

" Plugins
call plug#begin('~/.vim/plugged')

"Themes plugins
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'

"Languages
Plug 'vimwiki/vimwiki'

"Git tools
Plug 'tpope/vim-fugitive'
Plug 'Xuyuanp/nerdtree-git-plugin'

"Coding tools
Plug 'dense-analysis/ale'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'yggdroot/indentline'

"General tools
Plug 'mbbill/undotree'

call plug#end()


" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='term'


"NerdTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | NERDTree | endif

autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

autocmd BufEnter * if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif


" VimWiki
let g:vimwiki_list = [{'path': '~/Documents/vimwiki/'}]


" ALE
let g:ale_linters={'python': ['pylint']}
let g:ale_fixers={'python':['black']}
let g:ale_fix_on_save = 1
