# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# HOMEBREW
eval "$(/opt/homebrew/bin/brew shellenv)"

# ZINIT
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"


# PLUGINS
# THEME
zinit ice depth=1; zinit light romkatv/powerlevel10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# big three
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions

# another
zinit light Aloxaf/fzf-tab

# COMPLETIONS
setopt complete_aliases
autoload -U compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
source <(werf completion --shell=zsh)
source /Users/gnikishin/yandex-cloud/completion.zsh.inc

# HISTORY
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# KEYBINDS
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# SHELL INTEGRATIONS
eval "$(fzf --zsh)"

# SSH AGENT
export SSH_ASKPASS=/usr/local/bin/ssh-askpass
launchctl setenv SSH_ASKPASS $SSH_ASKPASS
SSH_ENV="/tmp/.ssh_environment_added"
env_display="`/bin/launchctl getenv DISPLAY`"
if [[ "x${env_display}" == "x" ]]; then
	/bin/launchctl setenv DISPLAY :0
fi

function start_agent {
    echo "Initializing new SSH agent..."
    echo > "${SSH_ENV}"
    /usr/bin/ssh-add -c $HOME/.ssh/id_rsa; # my key
    /usr/bin/ssh-add -c $HOME/.ssh/github_personal; # personal repos
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    ps -ef | grep ssh-agent > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi

h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/known_hosts ]]; then
  h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:scp:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

# TOOLS
# YC cli
# The next line updates PATH for Yandex Cloud CLI.
if [ -f '/Users/gnikishin/yandex-cloud/path.bash.inc' ]; then source '/Users/gnikishin/yandex-cloud/path.bash.inc'; fi
# The next line enables shell command completion for yc.
if [ -f '/Users/gnikishin/yandex-cloud/completion.zsh.inc' ]; then source '/Users/gnikishin/yandex-cloud/completion.zsh.inc'; fi

# ALIASES
alias ls='ls --color'
alias tn="tmux new -s $1"
alias ssh='sshrc'
